In [4]:
import pandas as pd

In [5]:
# !wget https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv

In [6]:
url = 'https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv'

In [7]:
df_zones = pd.read_csv(url)
df_zones.head(5)

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [11]:
df_zones.info()

<class 'pandas.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       264 non-null    str
 2   Zone          264 non-null    str
 3   service_zone  263 non-null    str
dtypes: int64(1), str(3)
memory usage: 17.0 KB

In [21]:
df_zones.isnull().sum()

LocationID      0
Borough         1
Zone            1
service_zone    2
dtype: int64

In [20]:
df_zones.loc[:, df_zones.isna().any()]

           Borough                     Zone service_zone
0              EWR           Newark Airport          EWR
1           Queens              Jamaica Bay    Boro Zone
2            Bronx  Allerton/Pelham Gardens    Boro Zone
3        Manhattan            Alphabet City  Yellow Zone
4    Staten Island            Arden Heights    Boro Zone
..             ...                      ...          ...
260      Manhattan       World Trade Center  Yellow Zone
261      Manhattan           Yorkville East  Yellow Zone
262      Manhattan           Yorkville West  Yellow Zone
263        Unknown                      NaN          NaN
264            NaN           Outside of NYC          NaN

[265 rows x 3 columns]

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi') #Connect DB

In [ ]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace') # insert only header in db

In [ ]:
# divide source into chunk using iterator
# df_iter = pd.read_csv(
#     prefix + 'yellow_tripdata_2021-01.csv.gz',
#     dtype=dtype,
#     parse_dates=parse_dates,
#     iterator=True,
#     chunksize=100000
# )
# df = next(df_iter) # next iter

In [ ]:
for df_chunk in tqdm(df_iter):
    # print(len(df_chunk))
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')